<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://univalle.edu/servicios" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" name="SWReciclaje" targetNamespace="http://univalle.edu/servicios" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://univalle.edu/servicios" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="ObtenerInformacionEstudiante">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="NTarjeta" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ObtenerInformacionEstudianteResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="ObtenerInformacionEstudianteResult" nillable="true" type="xs:anyType" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Desencriptar">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="cadena" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DesencriptarResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="DesencriptarResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Encriptar">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="cadena" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="EncriptarResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="EncriptarResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="EDefecto">
        <xs:sequence>
          <xs:element minOccurs="0" name="Clase" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Excepcion" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Mensaje" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Metodo" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="Servicio" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="TipoDefecto" type="tns:TTipoDefecto" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="EDefecto" nillable="true" type="tns:EDefecto" />
      <xs:simpleType name="TTipoDefecto">
        <xs:restriction base="xs:string">
          <xs:enumeration value="Ninguno" />
          <xs:enumeration value="Comunicacion" />
          <xs:enumeration value="BaseDatos" />
          <xs:enumeration value="Codificacion" />
          <xs:enumeration value="Falla" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="TTipoDefecto" nillable="true" type="tns:TTipoDefecto" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="ISWReciclaje_ObtenerInformacionEstudiante_InputMessage">
    <wsdl:part name="parameters" element="tns:ObtenerInformacionEstudiante" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_ObtenerInformacionEstudiante_OutputMessage">
    <wsdl:part name="parameters" element="tns:ObtenerInformacionEstudianteResponse" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_ObtenerInformacionEstudiante_EDefectoFault_FaultMessage">
    <wsdl:part xmlns:q1="http://schemas.datacontract.org/2004/07/" name="detail" element="q1:EDefecto" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_Desencriptar_InputMessage">
    <wsdl:part name="parameters" element="tns:Desencriptar" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_Desencriptar_OutputMessage">
    <wsdl:part name="parameters" element="tns:DesencriptarResponse" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_Desencriptar_EDefectoFault_FaultMessage">
    <wsdl:part xmlns:q2="http://schemas.datacontract.org/2004/07/" name="detail" element="q2:EDefecto" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_Encriptar_InputMessage">
    <wsdl:part name="parameters" element="tns:Encriptar" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_Encriptar_OutputMessage">
    <wsdl:part name="parameters" element="tns:EncriptarResponse" />
  </wsdl:message>
  <wsdl:message name="ISWReciclaje_Encriptar_EDefectoFault_FaultMessage">
    <wsdl:part xmlns:q3="http://schemas.datacontract.org/2004/07/" name="detail" element="q3:EDefecto" />
  </wsdl:message>
  <wsdl:portType name="ISWReciclaje">
    <wsdl:operation name="ObtenerInformacionEstudiante">
      <wsdl:input wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/ObtenerInformacionEstudiante" message="tns:ISWReciclaje_ObtenerInformacionEstudiante_InputMessage" />
      <wsdl:output wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/ObtenerInformacionEstudianteResponse" message="tns:ISWReciclaje_ObtenerInformacionEstudiante_OutputMessage" />
      <wsdl:fault wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/ObtenerInformacionEstudianteEDefectoFault" name="EDefectoFault" message="tns:ISWReciclaje_ObtenerInformacionEstudiante_EDefectoFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="Desencriptar">
      <wsdl:input wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/Desencriptar" message="tns:ISWReciclaje_Desencriptar_InputMessage" />
      <wsdl:output wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/DesencriptarResponse" message="tns:ISWReciclaje_Desencriptar_OutputMessage" />
      <wsdl:fault wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/DesencriptarEDefectoFault" name="EDefectoFault" message="tns:ISWReciclaje_Desencriptar_EDefectoFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="Encriptar">
      <wsdl:input wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/Encriptar" message="tns:ISWReciclaje_Encriptar_InputMessage" />
      <wsdl:output wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/EncriptarResponse" message="tns:ISWReciclaje_Encriptar_OutputMessage" />
      <wsdl:fault wsaw:Action="http://univalle.edu/servicios/ISWReciclaje/EncriptarEDefectoFault" name="EDefectoFault" message="tns:ISWReciclaje_Encriptar_EDefectoFault_FaultMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_ISWReciclaje" type="tns:ISWReciclaje">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ObtenerInformacionEstudiante">
      <soap:operation soapAction="http://univalle.edu/servicios/ISWReciclaje/ObtenerInformacionEstudiante" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="EDefectoFault">
        <soap:fault use="literal" name="EDefectoFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="Desencriptar">
      <soap:operation soapAction="http://univalle.edu/servicios/ISWReciclaje/Desencriptar" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="EDefectoFault">
        <soap:fault use="literal" name="EDefectoFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="Encriptar">
      <soap:operation soapAction="http://univalle.edu/servicios/ISWReciclaje/Encriptar" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="EDefectoFault">
        <soap:fault use="literal" name="EDefectoFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SWReciclaje">
    <wsdl:port name="BasicHttpBinding_ISWReciclaje" binding="tns:BasicHttpBinding_ISWReciclaje">
      <soap:address location="http://bridgem3.univalle.edu/SWReciclaje/SWReciclaje.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>